### ISSUE TITLE
Manual duration: only 5 or 10 minutes

### ISSUE THREAD

**Issue by rsporny** [spobel/homebridge-gpio-irrigationsystem#1]
Hi,
Is it possible to add more options when triggering sprinklers manually from homekit? Now it shows only 5 and 10 min duration.

**Comment by spobel** [comment]
Hi,
unfortunately, this is not a setting of the accessories. The pre-defined timer values are specified by the operating system. These were removed with the iOS 14 update. Hopefully these will be added again, I'll be waiting for them myself.

https://github.com/homebridge/HAP-NodeJS/issues/857
Since this issue is being pursued in the main project, I close this issue.

Thanks for reporting!
